# .github/workflows/ci.yml

name: CI for Sample Project

# このワークフローを実行するトリガー
on:
  push:
    branches:
      - main  # mainブランチへのプッシュ時に実行
  pull_request:
    branches:
      - main  # mainブランチへのプルリクエスト時に実行

# ジョブの定義
jobs:
  test:
    runs-on: ubuntu-latest  # GitHub Actionsで利用するランナー（環境）

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Pythonをセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0'  # 使用するPythonのバージョン

      # 必要なパッケージのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # テストの実行
      - name: Run tests
        run: pytest  # pytestを実行
